services:
  - type: web
    name: gcs-app
    runtime: docker
    dockerfilePath: ./Dockerfile

    plan: free

    healthCheckPath: /health

    envVars:
      # Te trzy pobierane z Render Secret (ustaw w dashboardzie)
      - key: SECRET_KEY
        sync: false     
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: DRONE_API_KEY
        sync: false

      - key: DATABASE_URL
        fromDatabase:
          name: gcs-db
          property: connectionString

      - key: FLASK_DEBUG
        value: "0"

databases:
  - name: gcs-db
    plan: free           
    databaseName: gcs_db
    user: gcs_user
